/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s_seguimiento_pacientes;


import plugins.TextPrompt;
import java.io.File;
import javax.swing.JOptionPane;
import org.omg.CORBA.ORB;
import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NameComponent;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;
import org.omg.PortableServer.POAManagerPackage.AdapterInactive;
import org.omg.PortableServer.POAPackage.ServantNotActive;
import org.omg.PortableServer.POAPackage.WrongPolicy;

/**
 *
 * @author Luis Romero - Santiago Cordoba
 */
public class ConexionServidor2GUI extends javax.swing.JFrame {

    /**
     * Creates new form ConexionServidor1GUI
     */
    public ConexionServidor2GUI() {
        initComponents();
        
        TextPrompt textDireccionIP = new TextPrompt("Dirección IP", txtDireccionIPConexionServidor2);
        TextPrompt textPuerto = new TextPrompt("Puerto", txtPuertoConexionServidor2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConexionServidor2 = new javax.swing.JPanel();
        lbServidor = new javax.swing.JLabel();
        lbConexionServidor = new javax.swing.JLabel();
        lbDireccionIP = new javax.swing.JLabel();
        lbPuerto = new javax.swing.JLabel();
        txtDireccionIPConexionServidor2 = new javax.swing.JTextField();
        txtPuertoConexionServidor2 = new javax.swing.JTextField();
        btnConectarServidor2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConexionServidor2.setPreferredSize(new java.awt.Dimension(341, 253));

        lbServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servidor.png"))); // NOI18N

        lbConexionServidor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbConexionServidor.setText("Conexión Servidor 2");

        lbDireccionIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/direccion-ip.png"))); // NOI18N

        lbPuerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llave-de-casa.png"))); // NOI18N

        txtDireccionIPConexionServidor2.setText("localhost");

        txtPuertoConexionServidor2.setText("5001");
        txtPuertoConexionServidor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoConexionServidor2KeyTyped(evt);
            }
        });

        btnConectarServidor2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnConectarServidor2.setText("¡Conectar Servidor!");
        btnConectarServidor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarServidor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConexionServidor2Layout = new javax.swing.GroupLayout(pnlConexionServidor2);
        pnlConexionServidor2.setLayout(pnlConexionServidor2Layout);
        pnlConexionServidor2Layout.setHorizontalGroup(
            pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConexionServidor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbServidor)
                    .addGroup(pnlConexionServidor2Layout.createSequentialGroup()
                        .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPuerto)
                            .addComponent(lbDireccionIP))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConexionServidor)
                    .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPuertoConexionServidor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtDireccionIPConexionServidor2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlConexionServidor2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnConectarServidor2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConexionServidor2Layout.setVerticalGroup(
            pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConexionServidor2Layout.createSequentialGroup()
                .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConexionServidor2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbConexionServidor))
                    .addGroup(pnlConexionServidor2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbServidor)))
                .addGap(20, 20, 20)
                .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDireccionIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDireccionIPConexionServidor2))
                .addGap(18, 18, 18)
                .addGroup(pnlConexionServidor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPuertoConexionServidor2))
                .addGap(18, 18, 18)
                .addComponent(btnConectarServidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConexionServidor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConexionServidor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPuertoConexionServidor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoConexionServidor2KeyTyped
        char validarNumero = evt.getKeyChar();
        if (Character.isLetter(validarNumero)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar números.");
        }
    }//GEN-LAST:event_txtPuertoConexionServidor2KeyTyped

    private void btnConectarServidor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarServidor2ActionPerformed
        int numPuertoRMIRegistry = 0;
        String direccionIpRMIRegistry = "";

        direccionIpRMIRegistry = txtDireccionIPConexionServidor2.getText();       
        numPuertoRMIRegistry = Integer.parseInt(txtPuertoConexionServidor2.getText());
        
        try{
            if (txtDireccionIPConexionServidor2.getText().equals("") && txtPuertoConexionServidor2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "No puede haber datos vacios");
            }else{
                String[] vec = new String[4];//almacena la información para localizar el ns
                vec[0] = "-ORBInitialHost";
                vec[1] = direccionIpRMIRegistry;
                vec[2] = "-ORBInitialPort";
                vec[3] = String.valueOf(numPuertoRMIRegistry);

                GestionNotificacionesImpl objRemoto = new GestionNotificacionesImpl();
                inicializarORB(vec, objRemoto);
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnConectarServidor2ActionPerformed

    private static void inicializarORB(String[] vec, GestionNotificacionesImpl objRemoto) throws ServantNotActive, WrongPolicy, org.omg.CORBA.ORBPackage.InvalidName, AdapterInactive, InvalidName, NotFound, CannotProceed, org.omg.CosNaming.NamingContextPackage.InvalidName {
        // crea e inicia el ORB
        File file1 = new File("src/CarpetaTXT/historialTGI.txt");
        File file2 = new File("src/CarpetaTXT/listadoTGIAprobados.txt");
        if (file1.exists() && !file1.isDirectory()) {
            file1.delete();
        }
        if (file2.exists()) {
            file2.delete();
        }

        ORB orb = ORB.init(vec, null);
        POA rootpoa = POAHelper.narrow(orb.resolve_initial_references("RootPOA"));
        rootpoa.the_POAManager().activate();

        //*** se genera la referencia del servant
        org.omg.CORBA.Object obj = rootpoa.servant_to_reference(objRemoto);
        SSeguimientoPacientes href = SSeguimientoPacientesHelper.narrow(obj);

        // se obtiene un link al name service
        org.omg.CORBA.Object objref = orb.resolve_initial_references("NameService");
        NamingContextExt ncref = NamingContextExtHelper.narrow(objref);

        // *** se realiza el binding de la referencia del servant en el N_S ***
        String name = "seguimiento";
        NameComponent path[] = ncref.to_name(name);
        ncref.rebind(path, href);
        // esperan por las invocaciones desde los clientes
        System.out.println("El Servidor esta listo y esperando ...");
        orb.run();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionServidor2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionServidor2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionServidor2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionServidor2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionServidor2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarServidor2;
    private javax.swing.JLabel lbConexionServidor;
    private javax.swing.JLabel lbDireccionIP;
    private javax.swing.JLabel lbPuerto;
    private javax.swing.JLabel lbServidor;
    private javax.swing.JPanel pnlConexionServidor2;
    private javax.swing.JTextField txtDireccionIPConexionServidor2;
    private javax.swing.JTextField txtPuertoConexionServidor2;
    // End of variables declaration//GEN-END:variables
}
