/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import S_Gestion_Pacientes.sop_rmi.GestionUsuariosInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Romero - Santiago Cordoba
 */
public class GUIAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdministrador
     */
    private static GestionUsuariosInt objRemotoU1;
    
    public GUIAdministrador(GestionUsuariosInt objRemotoU) {
        objRemotoU1 = objRemotoU;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public GUIAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdministrador = new javax.swing.JPanel();
        lbTituloAdmin = new javax.swing.JLabel();
        btnRegistrarAdministrador = new javax.swing.JButton();
        btnConsultarAdministrador = new javax.swing.JButton();
        btnSalirAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbTituloAdmin.setText("Menú Administrador");

        btnRegistrarAdministrador.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnRegistrarAdministrador.setText("Registrar Personal");
        btnRegistrarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAdministradorActionPerformed(evt);
            }
        });

        btnConsultarAdministrador.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnConsultarAdministrador.setText("Consultar Personal");
        btnConsultarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAdministradorActionPerformed(evt);
            }
        });

        btnSalirAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnSalirAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdministradorLayout = new javax.swing.GroupLayout(pnlAdministrador);
        pnlAdministrador.setLayout(pnlAdministradorLayout);
        pnlAdministradorLayout.setHorizontalGroup(
            pnlAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministradorLayout.createSequentialGroup()
                .addGroup(pnlAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdministradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalirAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTituloAdmin))
                    .addGroup(pnlAdministradorLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(pnlAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarAdministrador)
                            .addComponent(btnConsultarAdministrador))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pnlAdministradorLayout.setVerticalGroup(
            pnlAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministradorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTituloAdmin)
                    .addComponent(btnSalirAdministrador))
                .addGap(79, 79, 79)
                .addComponent(btnRegistrarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAdministradorActionPerformed
        new GUIRegistrarUsuario(objRemotoU1).setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnRegistrarAdministradorActionPerformed

    private void btnConsultarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAdministradorActionPerformed
        new GUIConsultarUsuario(objRemotoU1).setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnConsultarAdministradorActionPerformed

    private void btnSalirAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAdministradorActionPerformed
        if (objRemotoU1 == null) {
            JOptionPane.showMessageDialog(null, "No hay conexion con el servidor para cerrar sesión.");
        } else {
            Object[] opciones = {"Aceptar", "Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Esta seguro que desea cerrar sesión?", "Mensaje de Confirmacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
            if (eleccion == JOptionPane.YES_OPTION) {
                new GUIIniciarSesion(objRemotoU1).setVisible(true);
                super.dispose();
            }
        }
    }//GEN-LAST:event_btnSalirAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarAdministrador;
    private javax.swing.JButton btnRegistrarAdministrador;
    private javax.swing.JButton btnSalirAdministrador;
    private javax.swing.JLabel lbTituloAdmin;
    private javax.swing.JPanel pnlAdministrador;
    // End of variables declaration//GEN-END:variables
}
