/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import S_Gestion_Pacientes.dto.FRCP01FormatoDTO;
import S_Gestion_Pacientes.dto.PersonalDTO;
import S_Gestion_Pacientes.sop_rmi.GestionInformesInt;
import S_Gestion_Pacientes.sop_rmi.GestionUsuariosInt;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Romero - Santiago Cordoba
 */
public class GUIConsultarFormatoFRCP01 extends javax.swing.JFrame {

    private static GestionUsuariosInt objRemotoU1;
    private static GestionInformesInt objRemotoI1;
    /**
     * Creates new form GUIConsultarFormatoFRCP01
     * @param objRemotoU
     * @param objRemotoI
     */
    
    public GUIConsultarFormatoFRCP01(GestionUsuariosInt objRemotoU, GestionInformesInt objRemotoI) {
        objRemotoU1 = objRemotoU;
        objRemotoI1 = objRemotoI;
        initComponents();
    }
    
    public GUIConsultarFormatoFRCP01(GestionInformesInt objRemotoI) {
        objRemotoI1 = objRemotoI;
        initComponents();
    }
    
    public GUIConsultarFormatoFRCP01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConsultarId = new javax.swing.JTextField();
        btnConsultarId = new javax.swing.JButton();
        lbNombreCompleto = new javax.swing.JLabel();
        txtConsultarNombreCompleto = new javax.swing.JLabel();
        lbConsultarFechaIngreso = new javax.swing.JLabel();
        txtConsultarFechaIngreso = new javax.swing.JLabel();
        lbConsultarOrdenApoyoEPS = new javax.swing.JLabel();
        txtConsultarOrdenApoyoEPS = new javax.swing.JLabel();
        lbConsultarHistoriaClinica = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsultarHistoriaClinica = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAtras.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("Consultar Formato FRCP-01");

        jLabel2.setText("Identificación:");

        txtConsultarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultarIdKeyTyped(evt);
            }
        });

        btnConsultarId.setText("Consultar");
        btnConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdActionPerformed(evt);
            }
        });

        lbNombreCompleto.setText("Nombre completo:");

        txtConsultarNombreCompleto.setText("-");

        lbConsultarFechaIngreso.setText("Fecha de Ingreso:");

        txtConsultarFechaIngreso.setText("-");

        lbConsultarOrdenApoyoEPS.setText("Orden de Apoyo de la Eps:");

        txtConsultarOrdenApoyoEPS.setText("-");

        lbConsultarHistoriaClinica.setText("Historia Clinica:");

        txtConsultarHistoriaClinica.setColumns(20);
        txtConsultarHistoriaClinica.setRows(5);
        txtConsultarHistoriaClinica.setEnabled(false);
        jScrollPane1.setViewportView(txtConsultarHistoriaClinica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNombreCompleto)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsultarNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbConsultarFechaIngreso)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsultarFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbConsultarOrdenApoyoEPS)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsultarOrdenApoyoEPS, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbConsultarHistoriaClinica)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCompleto)
                    .addComponent(txtConsultarNombreCompleto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarFechaIngreso)
                    .addComponent(txtConsultarFechaIngreso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarOrdenApoyoEPS)
                    .addComponent(txtConsultarOrdenApoyoEPS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultarHistoriaClinica)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Esta seguro que desea salir del consultar?", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            new GUIOpcionesAdminRecep(objRemotoU1, objRemotoI1).setVisible(true);
            super.dispose();
        } else {
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdActionPerformed
        if (objRemotoI1 == null) {
            JOptionPane.showMessageDialog(null, "No hay conexion con el servidor.");
        }else{
            if (!txtConsultarId.getText().isEmpty()) {
                txtConsultarNombreCompleto.setText("-");
                txtConsultarFechaIngreso.setText("-");
                txtConsultarOrdenApoyoEPS.setText("-");
                txtConsultarHistoriaClinica.setText("");
                int idConsultar = Integer.parseInt(txtConsultarId.getText());
                try{
                    
                    int IdValido = objRemotoI1.validarIdPaciente(idConsultar);
                    if (IdValido != 0) {
                        FRCP01FormatoDTO objFormato01 = objRemotoI1.consultarPersonalFRCP01(idConsultar);
                        if (objFormato01 != null) {
                            txtConsultarNombreCompleto.setText(objFormato01.getNombreCompleto());
                            txtConsultarFechaIngreso.setText(objFormato01.getFechaIngreso());
                            txtConsultarOrdenApoyoEPS.setText(objFormato01.getOrdenApoyoEPS());
                            txtConsultarHistoriaClinica.setText(objFormato01.getHistoriaClinica());
                        }else{
                            JOptionPane.showMessageDialog(null, "EL paciente con el id " + idConsultar + " no existe. ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "EL paciente con el id " + idConsultar + " no existe. ");
                    }
                }catch(RemoteException ex){
                    System.out.println("La operacion ha fallado, intente nuevamente...");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar una identificación válida.");
            }
        }
    }//GEN-LAST:event_btnConsultarIdActionPerformed

    private void txtConsultarIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarIdKeyTyped
        char validarNumero = evt.getKeyChar();
        if (Character.isLetter(validarNumero)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar números.");
        }
    }//GEN-LAST:event_txtConsultarIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConsultarFormatoFRCP01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConsultarId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConsultarFechaIngreso;
    private javax.swing.JLabel lbConsultarHistoriaClinica;
    private javax.swing.JLabel lbConsultarOrdenApoyoEPS;
    private javax.swing.JLabel lbNombreCompleto;
    private javax.swing.JLabel txtConsultarFechaIngreso;
    private javax.swing.JTextArea txtConsultarHistoriaClinica;
    private javax.swing.JTextField txtConsultarId;
    private javax.swing.JLabel txtConsultarNombreCompleto;
    private javax.swing.JLabel txtConsultarOrdenApoyoEPS;
    // End of variables declaration//GEN-END:variables
}
