/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import S_Gestion_Pacientes.dto.FRCP03FormatoDTO;
import S_Gestion_Pacientes.sop_rmi.GestionInformesInt;
import S_Gestion_Pacientes.sop_rmi.GestionUsuariosInt;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Romero - Santiago Cordoba
 */
public class GUIConsultarFormatoFRCP03 extends javax.swing.JFrame {

    /**
     * Creates new form GUIConsultarFormatoFRCP03
     * @param objRemotoU
     * @param objRemotoI
     */
    private static GestionUsuariosInt objRemotoU1;
    private static GestionInformesInt objRemotoI1;
    
    public GUIConsultarFormatoFRCP03(GestionUsuariosInt objRemotoU, GestionInformesInt objRemotoI) {
        objRemotoU1 = objRemotoU;
        objRemotoI1 = objRemotoI;
        initComponents();
    }
    
    public GUIConsultarFormatoFRCP03(GestionInformesInt objRemotoI) {
        objRemotoI1 = objRemotoI;
        initComponents();
    }
    
    public GUIConsultarFormatoFRCP03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbConsultarFormatoFRCP03 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lbIdentificacion = new javax.swing.JLabel();
        txtConsultarId = new javax.swing.JTextField();
        btnConsultarId = new javax.swing.JButton();
        lbConsultarNumeroFase = new javax.swing.JLabel();
        txtConsultarNumeroFase = new javax.swing.JLabel();
        lbConsultarFechaSesion = new javax.swing.JLabel();
        txtConsultarFechaSesion = new javax.swing.JLabel();
        txtConsultarNumeroSesion = new javax.swing.JLabel();
        lbConsultarNumeroSesion = new javax.swing.JLabel();
        lbConsultarPresionArterial = new javax.swing.JLabel();
        txtConsultarPresionArterial = new javax.swing.JLabel();
        txtConsultarFrecuenciaCardiacaInicial = new javax.swing.JLabel();
        lbConsultarFrecuenciaCardiacaInicial = new javax.swing.JLabel();
        txtConsultarFrecuenciaCardiacaFinal = new javax.swing.JLabel();
        lbConsultarFrecuenciaCardiacaFinal = new javax.swing.JLabel();
        lbConsultarSaturacionOxigeno = new javax.swing.JLabel();
        txtConsultarSaturacionOxigeno = new javax.swing.JLabel();
        txtConsultarEstadoPaciente = new javax.swing.JLabel();
        lbConsultarEstadoPaciente = new javax.swing.JLabel();
        lbConsultarObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsultarObservaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbConsultarFormatoFRCP03.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbConsultarFormatoFRCP03.setText("Consultar Formato FRCP-03");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lbIdentificacion.setText("Identificacion:");

        txtConsultarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultarIdKeyTyped(evt);
            }
        });

        btnConsultarId.setText("Consultar");
        btnConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdActionPerformed(evt);
            }
        });

        lbConsultarNumeroFase.setText("Número de Fase:");

        txtConsultarNumeroFase.setText("-");

        lbConsultarFechaSesion.setText("Fecha de Sesión:");

        txtConsultarFechaSesion.setText("-");

        txtConsultarNumeroSesion.setText("-");

        lbConsultarNumeroSesion.setText("Número de Sesión:");

        lbConsultarPresionArterial.setText("Presión Arterial:");

        txtConsultarPresionArterial.setText("-");

        txtConsultarFrecuenciaCardiacaInicial.setText("-");

        lbConsultarFrecuenciaCardiacaInicial.setText("Frecuencia Cardiaca Inicial:");

        txtConsultarFrecuenciaCardiacaFinal.setText("-");

        lbConsultarFrecuenciaCardiacaFinal.setText("Frecuencia Cardiaca Final:");

        lbConsultarSaturacionOxigeno.setText("Saturación Oxigeno:");

        txtConsultarSaturacionOxigeno.setText("-");

        txtConsultarEstadoPaciente.setText("-");

        lbConsultarEstadoPaciente.setText("Estado del Paciente:");

        lbConsultarObservaciones.setText("Observaciones:");

        txtConsultarObservaciones.setColumns(20);
        txtConsultarObservaciones.setRows(5);
        txtConsultarObservaciones.setEnabled(false);
        jScrollPane1.setViewportView(txtConsultarObservaciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbConsultarFormatoFRCP03))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdentificacion)
                            .addComponent(lbConsultarNumeroFase)
                            .addComponent(lbConsultarFechaSesion)
                            .addComponent(lbConsultarNumeroSesion)
                            .addComponent(lbConsultarPresionArterial)
                            .addComponent(lbConsultarFrecuenciaCardiacaInicial)
                            .addComponent(lbConsultarFrecuenciaCardiacaFinal)
                            .addComponent(lbConsultarSaturacionOxigeno)
                            .addComponent(lbConsultarEstadoPaciente)
                            .addComponent(lbConsultarObservaciones))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultarFechaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarNumeroFase, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarNumeroSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarPresionArterial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarFrecuenciaCardiacaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarFrecuenciaCardiacaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarSaturacionOxigeno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarEstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtConsultarId, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarId)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbConsultarFormatoFRCP03)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacion)
                    .addComponent(txtConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarNumeroFase)
                    .addComponent(txtConsultarNumeroFase))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarFechaSesion)
                    .addComponent(txtConsultarFechaSesion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarNumeroSesion)
                    .addComponent(txtConsultarNumeroSesion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarPresionArterial)
                    .addComponent(txtConsultarPresionArterial))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarFrecuenciaCardiacaInicial)
                    .addComponent(txtConsultarFrecuenciaCardiacaInicial))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarFrecuenciaCardiacaFinal)
                    .addComponent(txtConsultarFrecuenciaCardiacaFinal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarSaturacionOxigeno)
                    .addComponent(txtConsultarSaturacionOxigeno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsultarEstadoPaciente)
                    .addComponent(txtConsultarEstadoPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultarObservaciones)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Esta seguro que desea salir del consultar?", "Mensaje de Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            new GUIOpcionesFisio(objRemotoU1, objRemotoI1).setVisible(true);
            super.dispose();
        } else {
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdActionPerformed
        if (objRemotoI1 == null) {
            JOptionPane.showMessageDialog(null, "No hay conexion con el servidor.");
        }else{
            if (!txtConsultarId.getText().isEmpty()) {
                txtConsultarNumeroFase.setText("-");
                txtConsultarFechaSesion.setText("-");
                txtConsultarNumeroSesion.setText("-");
                txtConsultarPresionArterial.setText("-");
                txtConsultarFrecuenciaCardiacaInicial.setText("-");
                txtConsultarFrecuenciaCardiacaFinal.setText("-");
                txtConsultarSaturacionOxigeno.setText("-");
                txtConsultarEstadoPaciente.setText("-");
                txtConsultarObservaciones.setText("-");
                int idConsultar = Integer.parseInt(txtConsultarId.getText());
                try{
                    
                    int IdValido = objRemotoI1.validarIdPaciente(idConsultar);
                    if (IdValido != 0) {
                        FRCP03FormatoDTO objFormato03 = objRemotoI1.consultarPersonalFRCP03(idConsultar);
                        if (objFormato03 != null) {
                            txtConsultarNumeroFase.setText(String.valueOf(objFormato03.getNumeroFase()));
                            txtConsultarFechaSesion.setText(objFormato03.getFechaSesion());
                            txtConsultarNumeroSesion.setText(String.valueOf(objFormato03.getNumeroSesion()));
                            txtConsultarPresionArterial.setText(String.valueOf(objFormato03.getPresionArterial()));
                            txtConsultarFrecuenciaCardiacaInicial.setText(String.valueOf(objFormato03.getFrecuenciaCardiacaInicial()));
                            txtConsultarFrecuenciaCardiacaFinal.setText(String.valueOf(objFormato03.getFrecuenciaCardiacaFinal()));
                            txtConsultarSaturacionOxigeno.setText(String.valueOf(objFormato03.getSaturacionOxigeno()));
                            txtConsultarEstadoPaciente.setText(objFormato03.getEstadoPaciente());
                            txtConsultarObservaciones.setText(objFormato03.getObservaciones());
                        }else {
                            JOptionPane.showMessageDialog(null, "EL paciente con el id " + idConsultar + " no existe. ");
                        }
                    }else {
                        JOptionPane.showMessageDialog(null, "EL paciente con el id " + idConsultar + " no existe. ");
                    }
                }catch(RemoteException ex){
                    System.out.println("La operacion ha fallado, intente nuevamente...");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar una identificación válida.");
            }
        }
    }//GEN-LAST:event_btnConsultarIdActionPerformed

    private void txtConsultarIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarIdKeyTyped
        char validarNumero = evt.getKeyChar();
        if (Character.isLetter(validarNumero)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar números.");
        }
    }//GEN-LAST:event_txtConsultarIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarFormatoFRCP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConsultarFormatoFRCP03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConsultarId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConsultarEstadoPaciente;
    private javax.swing.JLabel lbConsultarFechaSesion;
    private javax.swing.JLabel lbConsultarFormatoFRCP03;
    private javax.swing.JLabel lbConsultarFrecuenciaCardiacaFinal;
    private javax.swing.JLabel lbConsultarFrecuenciaCardiacaInicial;
    private javax.swing.JLabel lbConsultarNumeroFase;
    private javax.swing.JLabel lbConsultarNumeroSesion;
    private javax.swing.JLabel lbConsultarObservaciones;
    private javax.swing.JLabel lbConsultarPresionArterial;
    private javax.swing.JLabel lbConsultarSaturacionOxigeno;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel txtConsultarEstadoPaciente;
    private javax.swing.JLabel txtConsultarFechaSesion;
    private javax.swing.JLabel txtConsultarFrecuenciaCardiacaFinal;
    private javax.swing.JLabel txtConsultarFrecuenciaCardiacaInicial;
    private javax.swing.JTextField txtConsultarId;
    private javax.swing.JLabel txtConsultarNumeroFase;
    private javax.swing.JLabel txtConsultarNumeroSesion;
    private javax.swing.JTextArea txtConsultarObservaciones;
    private javax.swing.JLabel txtConsultarPresionArterial;
    private javax.swing.JLabel txtConsultarSaturacionOxigeno;
    // End of variables declaration//GEN-END:variables
}
